-- DICT --
INSERT INTO dict(value, type, version) VALUES ('CREATED', 'CONTRACT_STATUS', '0')
INSERT INTO dict(value, type, version) VALUES ('ACCEPTED', 'CONTRACT_STATUS', '0')
INSERT INTO dict(value, type, version) VALUES ('COMPLETED', 'CONTRACT_STATUS', '0')
INSERT INTO dict(value, type, version) VALUES ('APPROVED', 'CONTRACT_STATUS', '0')
INSERT INTO dict(value, type, version) VALUES ('CANCELED', 'CONTRACT_STATUS', '0')
INSERT INTO dict(value, type, version) VALUES ('ICY', 'PLANET_TYPE', '0')
INSERT INTO dict(value, type, version) VALUES ('OCEAN', 'PLANET_TYPE', '0')
INSERT INTO dict(value, type, version) VALUES ('HOT', 'PLANET_TYPE', '0')
INSERT INTO dict(value, type, version) VALUES ('COLD', 'PLANET_TYPE', '0')
INSERT INTO dict(value, type, version) VALUES ('DESERT', 'PLANET_TYPE', '0')
INSERT INTO dict(value, type, version) VALUES ('EXTREME', 'PRIORITY', '0')
INSERT INTO dict(value, type, version) VALUES ('HIGH', 'PRIORITY', '0')
INSERT INTO dict(value, type, version) VALUES ('MEDIUM', 'PRIORITY', '0')
INSERT INTO dict(value, type, version) VALUES ('LOW', 'PRIORITY', '0')
INSERT INTO dict(value, type, version) VALUES ('ADMIN', 'USER_ROLE', '0')
INSERT INTO dict(value, type, version) VALUES ('HUNTER', 'USER_ROLE', '0')
INSERT INTO dict(value, type, version) VALUES ('CLIENT', 'USER_ROLE', '0')
INSERT INTO dict(value, type, version) VALUES ('IMPOSSIBLE', 'THREAT_LEVEL', '0')
INSERT INTO dict(value, type, version) VALUES ('EXTREME', 'THREAT_LEVEL', '0')
INSERT INTO dict(value, type, version) VALUES ('HIGH', 'THREAT_LEVEL', '0')
INSERT INTO dict(value, type, version) VALUES ('MEDIUM', 'THREAT_LEVEL', '0')
INSERT INTO dict(value, type, version) VALUES ('LOW', 'THREAT_LEVEL', '0')
INSERT INTO dict(value, type, version) VALUES ('NONE', 'THREAT_LEVEL', '0')
-- GALAXY --
INSERT INTO galaxy(name, version) VALUES ('Galaxy Far, Far Away', '0')
INSERT INTO galaxy(name, version) VALUES ('Eye of Sauron Galaxy', '0')
INSERT INTO galaxy(name, version) VALUES ('Ymielinium Galaxy', '0')
INSERT INTO galaxy(name, version) VALUES ('Cosmos Redshift 7', '0')
-- PLANET --
INSERT INTO planet(name, planet_type, galaxy_id, version) VALUES ('Tatooine', 'ICY','1', '0')
INSERT INTO planet(name, planet_type, galaxy_id, version) VALUES ('Alderan', 'OCEAN','1', '0')
INSERT INTO planet(name, planet_type, galaxy_id, version) VALUES ('Hoth', 'HOT','1', '0')
INSERT INTO planet(name, planet_type, galaxy_id, version) VALUES ('Bespin', 'COLD','1', '0')
INSERT INTO planet(name, planet_type, galaxy_id, version) VALUES ('Coruscant', 'DESERT','1', '0')

INSERT INTO planet(name, planet_type, galaxy_id, version) VALUES ('Middle-Earth', 'OCEAN','2', '0')

INSERT INTO planet(name, planet_type, galaxy_id, version) VALUES ('Ymielin', 'DESERT','3', '0')

INSERT INTO planet(name, planet_type, galaxy_id, version) VALUES ('Centax-1', 'COLD','4', '0')
INSERT INTO planet(name, planet_type, galaxy_id, version) VALUES ('Centax-2', 'COLD','4', '0')
INSERT INTO planet(name, planet_type, galaxy_id, version) VALUES ('Centax-3', 'ICY','4', '0')
-- DISTRICT --
INSERT INTO district(name, planet_id, version) VALUES ('Federal District','1', '0')
INSERT INTO district(name, planet_id, version) VALUES ('CoCo Town','1', '0')
INSERT INTO district(name, planet_id, version) VALUES ('Senate Plaza','2', '0')
INSERT INTO district(name, planet_id, version) VALUES ('Mid-Rim','3', '0')
INSERT INTO district(name, planet_id, version) VALUES ('Old District','4', '0')
INSERT INTO district(name, planet_id, version) VALUES ('Orowood','4', '0')
INSERT INTO district(name, planet_id, version) VALUES ('Pillar Zone','5', '0')

INSERT INTO district(name, planet_id, version) VALUES ('Mordor','6', '0')
INSERT INTO district(name, planet_id, version) VALUES ('Gondor','6', '0')
INSERT INTO district(name, planet_id, version) VALUES ('Rohan','6', '0')
INSERT INTO district(name, planet_id, version) VALUES ('Eriador','6', '0')

INSERT INTO district(name, planet_id, version) VALUES ('Cisowiec','7', 0)
INSERT INTO district(name, planet_id, version) VALUES ('Jamnice','7', 0)
INSERT INTO district(name, planet_id, version) VALUES ('Pasieczki','7', 0)

INSERT INTO district(name, planet_id, version) VALUES ('Quadrant A-4','8', '0')
INSERT INTO district(name, planet_id, version) VALUES ('Quadrant A-89','8', '0')
INSERT INTO district(name, planet_id, version) VALUES ('Sector 2-12','9', '0')
INSERT INTO district(name, planet_id, version) VALUES ('Sector 1459','9', '0')
INSERT INTO district(name, planet_id, version) VALUES ('Grid 17','10', '0')
INSERT INTO district(name, planet_id, version) VALUES ('Grid 19','10', '0')
--PERSON--
INSERT INTO person(alias, birth_date, name, version) VALUES ('admin1', parsedatetime('01-01-2000', 'dd-MM-yyyy'), 'Staszek', '0')
INSERT INTO person(alias, birth_date, name, version) VALUES ('hunter1', parsedatetime('01-01-2000', 'dd-MM-yyyy'), 'Jasiek', '0')
INSERT INTO person(alias, birth_date, name, version) VALUES ('client1', parsedatetime('01-01-2000', 'dd-MM-yyyy'), 'Janusz', '0')
INSERT INTO person(alias, birth_date, name, version) VALUES ('DarthVader', parsedatetime('01-01-2000', 'dd-MM-yyyy'), 'DarthVader', '0')
INSERT INTO person(alias, birth_date, name, version) VALUES ('Thanos', parsedatetime('01-01-2000', 'dd-MM-yyyy'), 'Thanos', 0)
INSERT INTO person(alias, birth_date, name, version) VALUES ('Stormtrooper', parsedatetime('01-01-2000', 'dd-MM-yyyy'), 'Stormtrooper', '0')
--USER_ACCOUNT--
INSERT INTO user_account (enabled, password, user_role, username, person_id) VALUES (true, 'admin', 'ADMIN', 'admin', '1')
INSERT INTO user_account (enabled, password, user_role, username, person_id) VALUES (true, 'hunter', 'HUNTER', 'hunter', '2')
INSERT INTO user_account (enabled, password, user_role, username, person_id) VALUES (true, 'client', 'CLIENT', 'client', '3')
--VICTIM--
INSERT INTO victim(age, force_sensitive, threat_level, person_id) VALUES ('19','true','IMPOSSIBLE','4')
INSERT INTO victim(age, force_sensitive, threat_level, person_id) VALUES ('19','true','EXTREME','5')
INSERT INTO victim(age, force_sensitive, threat_level, person_id) VALUES ('19','true','MEDIUM','6')
--REVIEW--
INSERT INTO review(comment, rating, would_recommend, version) VALUES ('Wszystko ok polecam huntera','8', 'true', '0')
--CONTRACT--
INSERT INTO contract(contract_status, from_date, name, payment, priority, thru_date, client_id, district_id, hunter_id, review_id, victim_id, version) VALUES ('COMPLETED', parsedatetime('01-10-2019', 'dd-MM-yyyy'), 'Quick job', '9000', 'HIGH', parsedatetime('30-10-2019', 'dd-MM-yyyy'), '3', '15', '2', '1', '6', '0')
INSERT INTO contract(contract_status, from_date, name, payment, priority, thru_date, client_id, district_id, hunter_id, review_id, victim_id, version) VALUES ('CREATED', parsedatetime('01-11-2019', 'dd-MM-yyyy'), 'Training Day', '99999999', 'EXTREME', parsedatetime('30-10-2020', 'dd-MM-yyyy'), '3', '1', null, null, '4', '0')