-- DICT --
INSERT INTO dict(value, type, version) VALUES ('CREATED', 'CONTRACT_STATUS', 0)
INSERT INTO dict(value, type, version) VALUES ('ACCEPTED', 'CONTRACT_STATUS', 0)
INSERT INTO dict(value, type, version) VALUES ('COMPLETED', 'CONTRACT_STATUS', 0)
INSERT INTO dict(value, type, version) VALUES ('APPROVED', 'CONTRACT_STATUS', 0)
INSERT INTO dict(value, type, version) VALUES ('CANCELED', 'CONTRACT_STATUS', 0)
INSERT INTO dict(value, type, version) VALUES ('ICY', 'PLANET_TYPE', 0)
INSERT INTO dict(value, type, version) VALUES ('OCEAN', 'PLANET_TYPE', 0)
INSERT INTO dict(value, type, version) VALUES ('HOT', 'PLANET_TYPE', 0)
INSERT INTO dict(value, type, version) VALUES ('COLD', 'PLANET_TYPE', 0)
INSERT INTO dict(value, type, version) VALUES ('DESERT', 'PLANET_TYPE', 0)
INSERT INTO dict(value, type, version) VALUES ('EXTREME', 'PRIORITY', 0)
INSERT INTO dict(value, type, version) VALUES ('HIGH', 'PRIORITY', 0)
INSERT INTO dict(value, type, version) VALUES ('MEDIUM', 'PRIORITY', 0)
INSERT INTO dict(value, type, version) VALUES ('LOW', 'PRIORITY', 0)
INSERT INTO dict(value, type, version) VALUES ('ADMIN', 'USER_ROLE', 0)
INSERT INTO dict(value, type, version) VALUES ('HUNTER', 'USER_ROLE', 0)
INSERT INTO dict(value, type, version) VALUES ('CLIENT', 'USER_ROLE', 0)
INSERT INTO dict(value, type, version) VALUES ('IMPOSSIBLE', 'THREAT_LEVEL', 0)
INSERT INTO dict(value, type, version) VALUES ('EXTREME', 'THREAT_LEVEL', 0)
INSERT INTO dict(value, type, version) VALUES ('HIGH', 'THREAT_LEVEL', 0)
INSERT INTO dict(value, type, version) VALUES ('MEDIUM', 'THREAT_LEVEL', 0)
INSERT INTO dict(value, type, version) VALUES ('LOW', 'THREAT_LEVEL', 0)
INSERT INTO dict(value, type, version) VALUES ('NONE', 'THREAT_LEVEL', 0)
-- GALAXY --
